/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    KaleidosyncStage: typeof import('./src/components/KaleidosyncStage.vue')['default']
    ProjectionFaceCanvas: typeof import('./src/components/ProjectionFaceCanvas.vue')['default']
    ProjectionMapper: typeof import('./src/components/ProjectionMapper.vue')['default']
    ProjectionMapperPanel: typeof import('./src/components/ProjectionMapperPanel.vue')['default']
    StageSketchMesh: typeof import('./src/components/StageSketchMesh.vue')['default']
  }
}
